### ISSUE TITLE
HID devices not ready when main.py starts

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_HID#13]
On some hosts (reported on a Windows 10 machine), `main.py` can start before the HID devices are ready on the host side. Examples: 
https://forums.adafruit.com/viewtopic.php?f=52&t=125560#p629406
https://forums.adafruit.com/viewtopic.php?f=52&t=130143
Also reported in Discord (thanks @PhunkMaster)

I added `time.sleep(1)` to some of the HID examples (e.g., https://learn.adafruit.com/adafruit-circuit-playground-express?view=all#circuitpython-hid-keyboard), but this should really be handled in the library or possibly in the native implementation. The creation operations like `Mouse()` and `Keyboard()` could sleep and retry after failure, possibly just once.

**Comment by PhunkMaster** [comment]
Per @dhalbert 's request, here was the failing code.

`import board
import time
import digitalio
import adafruit_dotstar
from adafruit_hid.mouse import Mouse

mouse = Mouse()
led = digitalio.DigitalInOut(board.D13)
led.direction = digitalio.Direction.OUTPUT
led2 = adafruit_dotstar.DotStar(board.APA102_SCK, board.APA102_MOSI, 1)

led2[0] = (129, 0, 250)
while True:
  led.value = False
  led2.brightness = 0.1
  mouse.move(x=1)
  time.sleep(.1)
  mouse.move(y=1)
  time.sleep(.1)
  mouse.move(x=-1)
  time.sleep(.1)
  mouse.move(y=-1)
  led2.brightness = 0.0
  time.sleep(1.0)`
