### ISSUE TITLE
Negative mouse movement not working in CP 4.x

### ISSUE THREAD

**Issue by caternuson** [adafruit/Adafruit_CircuitPython_HID#37]
Re this thread:
https://forums.adafruit.com/viewtopic.php?f=60&t=152111

Guess this somehow worked in 3.x:
https://github.com/adafruit/Adafruit_CircuitPython_HID/blob/890c4c17dc068f74170ff750a77c0c96aa8c5fb5/adafruit_hid/mouse.py#L147-L148

**Comment by dhalbert** [comment]
I'll need to update the boards that freeze HID in (mainly CPX), because it will be broken there too.
