### ISSUE TITLE
Documentation and bundled examples may not match CircuitPython 5.x

### ISSUE THREAD

**Issue by jepler** [adafruit/Adafruit_CircuitPython_HID#49]
```
README.rst:    kbd = Keyboard()
README.rst:    kbd = Keyboard()
README.rst:    m = Mouse()
adafruit_hid/keyboard_layout_us.py:            kbd = Keyboard()
```

These now need `usb_hid.descriptors` passed to them.

**Comment by dherrada** [comment]
This appears to have been fixed in the README already. I just made the fix in keyboard_layout_us.py, and confirmed with grep that was all that was left.
