### ISSUE TITLE
Add multimedia keypress support

### ISSUE THREAD

**Issue by ladyada** [adafruit/Adafruit_CircuitPython_HID#5]
requires a different kind of report?
http://www.microchip.com/forums/m859944.aspx

**Comment by dhalbert** [comment]
We need to add the "Consumer Usage Page" (0x0C) to the USB HID descriptor for the keyboard, and then the report is different as well. So there are changes both in CPy itself and in the library.

**Comment by ladyada** [comment]
yah its a bit more work but MMKeys are really handy to make controllers for computers, i made a trinket + rotary encoder HID controller...would be rad if it controlled computer volume :)

**Comment by dhalbert** [comment]
I found that project and code. Will look into this. ASF3 doesn't appear to support this out of the box - we'll have to augment it. I'll look at ASF4 too.

**Comment by tannewt** [comment]
@dhalbert can you file an issue in adafruit/circuitpython for it and mark it for 3.0?
