### ISSUE TITLE
Fn Key Support

### ISSUE THREAD

**Issue by edm00se** [adafruit/Adafruit_CircuitPython_HID#92]
I'd like to be able to emit the media control key press for macOS, such as pause/play `Fn` + `F7`. From my looking through [`adafruit_hid.keycode`](https://github.com/adafruit/Adafruit_CircuitPython_HID/blob/main/adafruit_hid/keycode.py) and [documentation](https://circuitpython.readthedocs.io/projects/hid/en/latest/api.html#adafruit-hid-keycode-keycode) I don't currently believe this is supported but I'd love to see it made available.

**Comment by Neradoc** [comment]
Media keys are Consumer Controls. There is a short list available in the library:
https://docs.circuitpython.org/projects/hid/en/latest/api.html#adafruit-hid-consumer-control-code-consumercontrolcode
And you can supply any valid value as ints.

Here is the example code for ConsumerControl:
https://github.com/adafruit/Adafruit_CircuitPython_HID/blob/main/examples/hid_consumer_control_brightness.py

**Comment by edm00se** [comment]
Perfect! I'll need to re-work my macro but I think that example should get me headed in the right direction. Thank you.
